name: Github Build/Push Action
on:
  release:
      types: [created]
      
jobs:
  build-explorer:
    runs-on: ubuntu-20.04
    steps:
    -
      name: Checkout 
      uses: actions/checkout@v2

    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
    
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tf-explorer:${{ steps.get-latest-tag.outputs.tag }}