name: Github Build Action
on:
  push:
    branches:
      - master_github_actions # TODO change this to master, use tag
    # tags:
    #  - v3.0.0-rc*

  # pull_request: ## TODO uncomment this to make it also with PR
  #   branches:
  #     - 'main'
jobs:
  build-explorer:
    runs-on: ubuntu-20.04
    steps:
    -
        name: Checkout 
        uses: actions/checkout@v2
    
    -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/explorer-test:latest